---
server:
 port: 9090
 
spring:
  application:
    name: PET-OWNER-SERVICE 
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        definition: http://localhost:8761/eureka
  
  instance:
    hostname: localhost
    
  